---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    # Check for updates once a day
    schedule:
      interval: daily
    allow:
      - dependency-type: all
  - package-ecosystem: github-actions
    directory: /
    # Check for updates once a week
    schedule:
      interval: weekly
