name: In tree build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Add requirements
      run: |
        python -m pip install --upgrade pip wheel setuptools jupyter

    - name: Build and install
      run: pip install --use-feature=in-tree-build --verbose ".[test]"

    - name: Unit test
      run: pytest tests/phik_python/test_phik.py -v

    - name: Integration test
      run: pytest tests/phik_python/integration/test_notebooks.py -v
